on:
  push:
    branches:
      - "main"
    paths:
      - "README.md"

jobs:
  build:
    permissions:
      contents: write # for git push

    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v3

      - name: Copy README from 'main'
        run: |
          cp -f README.md ${{ runner.temp }}/README.md

      - name: Checkout 'gh-pages'
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Sync README from 'main' to 'gh-pages'
        run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README from main"
          git push
